# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'google-examples-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for google-examples-swift
  pod 'Firebase/Core'
  pod 'FirebaseAnalytics'
  pod 'GoogleSignIn'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'GTMOAuth2'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'GoogleAPIClientForREST/Sheets'
  pod 'GoogleAPIClientForREST/Calendar'
  pod 'GoogleAPIClientForREST/YouTube'


  target 'google-examples-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'google-examples-swiftUITests' do
    # Pods for testing
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
    end
  end
end
end
